name: Testing Service

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout new code for testing
        uses: actions/checkout@v2
      - name: Setup go testing infrastructure
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Test partition service
        run: go test  ./...

      - name: Run Vet & Lint
        run: |
          go vet .
          golint -set_exit_status=1 .
