name: Testing Service

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout new code for testing
        uses: actions/checkout@v3
      - name: Setup go testing infrastructure
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Install dependencies
        run: |
          go version

      - name: Install tesseract dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates libtesseract-dev libleptonica-dev  tesseract-ocr-eng

      - name: Test ocr service
        run: go test  ./...

